# Arrays vs Lists

In [29]:
import numpy as np

In [4]:
dummy_list = [1, 2, 3, 4]

In [5]:
dummy_array = np.array([1, 2, 3, 4])

In [7]:
# Acessando elemento a elemento: 
print("--- List ---")
for each_item in dummy_list: 
    print(each_item)

print("--- Numpy Array ----")
for each_item in dummy_array: 
    print(each_item)

--- List ---
1
2
3
4
--- Numpy Array ----
1
2
3
4


In [10]:
# É possível adicionar items a uma lista
dummy_list = [1, 2, 3, 4] # Redeclarando a lista para não alterá-la futuramente
dummy_list.append(5)

print(dummy_list) 
print(dummy_list + [6]) # + funciona como concatenação

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


In [22]:
# No caso do array, não é possível fazer um append
try: 
    dummy_array.append(3)
except AttributeError as err: 
    print(f"Falha: {err}")

Falha: 'numpy.ndarray' object has no attribute 'append'


In [21]:
# Além disso, o operador "+" funciona de outra forma
# Nome técnico desse efeito é "Broadcasting"
print(dummy_array + np.array([3])) 

# No caso em que os tamanhos dos vetores casam, 
# a soma de vetores é realizada normalmente
print(dummy_array + np.array([6,5,4,3]))

# No caso em que os tamanhos não casam, ocorre um 
# ValueError
try: 
    print(dummy_array + np.array([3, 2]))
except ValueError as err: 
    #print("Não foi possível somar vetores de tamanhos diferentes")
    print(f"Erro: {err}")

[4 5 6 7]
[7 7 7 7]
Erro: operands could not be broadcast together with shapes (4,) (2,) 


In [32]:
# Em listas, as operações matemáticas tem que ser executadas elemento a elemento
squared_list = [element**2 for element in dummy_list]
print(squared_list)

# Em um np.array, as operações em geral são aplicadas elemento a elemento diretamente
print(dummy_array**2)
print(np.sqrt(dummy_array))
print(np.log(dummy_array))
print(np.exp(dummy_array))

[1, 4, 9, 16, 25]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


# Produto Escalar (Dot Product)
Para dois vetores $[a_1, \cdots, a_n]$ e $[b_1, \cdots, b_n]$: 
$$a \cdot b = \sum_{i=1}^n a_i b_i $$

In [33]:
# Uma possível implementação "do zero"
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

def my_dot_product(a, b): 
    dot = 0
    for i, j in zip(a, b): 
        dot += i*j
    return dot

print(my_dot_product(a, b))

35


In [37]:
# Fazendo isso com o numpy (duas formas)
print(np.sum(a * b))
print(np.dot(a, b))

35
35


# Teste de Velocidade

In [42]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
N = 100000

test1_start_time = datetime.now()
for n in range(N): 
    my_dot_product(a, b)
test1_duration = datetime.now() - test1_start_time

test2_start_time = datetime.now()
for n in range(N): 
    np.dot(a, b)
test2_duration = datetime.now() - test2_start_time

print(f"O teste 2 foi executado aproximadamente {round(test1_duration / test2_duration, 1)} vezes mais rápido.")

O teste 2 foi executado aproximadamente 20.5 vezes mais rápido.


# Matrizes
Em geral, as matrizes herdam praticamente todas as propriedades dos vetores. No entanto, tem algumas funções que são específicas para matrizes quadradas, como determinante e inversa.

In [61]:
dummy_matrix = np.array([[1, 2], [3, 4]])
print(dummy_matrix)

#Determinante
determinant = np.linalg.det(dummy_matrix)
print(f"Determinante da Matrix: \n{determinant}")

# Inversa
inverse_dummy_matrix = np.linalg.inv(dummy_matrix)
print(f"Matriz inversa: \n{inverse_dummy_matrix}")

# Traço
trace = np.trace(dummy_matrix)
print(f"Traço da matriz: \n{trace}")

# Diagonal em uma matriz
diag_vector = np.diag(dummy_matrix)
print(f"Vetor formado pelos elementos da diagonal da matriz: \n{diag_vector}")

# Diagonal em um vetor
diag_matrix = np.diag(diag_vector)
print(f"Matriz diagonal montada a partir dos elementos do vetor: \n{diag_matrix}")

[[1 2]
 [3 4]]
Determinante da Matrix: 
-2.0000000000000004
Matriz inversa: 
[[-2.   1. ]
 [ 1.5 -0.5]]
Traço da matriz: 
5
Vetor formado pelos elementos da diagonal da matriz: 
[1 4]
Matriz diagonal montada a partir dos elementos do vetor: 
[[1 0]
 [0 4]]


# Autovalores e Autovetores

Obter as soluções para a equação matricial dada por: 

$$ Av = \lambda v \Longrightarrow (A- \lambda I)v = 0 $$

Menção Honrosa: numpy.linalg.eigh - autovalor e autovetor da matrix hermiteana. 

In [64]:
autovalores, autovetores = np.linalg.eig(dummy_matrix)

print(autovalores)
print(autovetores)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Sistema Linear

Solução para o sistema: 

$$ \begin{bmatrix} 1 & 1 \\ 1.5 & 4 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} 2200 \\ 5050 \end{bmatrix}$$

$$ Ax = B$$

$$ x = A^{-1} B $$

In [70]:
matriz_de_coeficientes = np.array([[1, 1], [1.5, 4]])
matriz_de_saídas = np.array([[2200], [5050]])

# Solução "Na raça"
inversa_da_matriz_de_coeficientes = np.linalg.inv(matriz_de_coeficientes)
X_raça = np.matmul(inversa_da_matriz_de_coeficientes, matriz_de_saídas)
print(X_raça)

# Solução otimizada, linalg.solve!
X_otimizado = np.linalg.solve(matriz_de_coeficientes, matriz_de_saídas)
print(X_otimizado)

[[1500.]
 [ 700.]]
[[1500.]
 [ 700.]]
